services:
  web:
    build: .
    volumes:
#      - .:/app
      # - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - 8008:8000
    command: python -m gunicorn --bind 0.0.0.0:8000 --workers 4 --keep-alive=2 core.wsgi:application
    restart: unless-stopped
#    entrypoint: /app/entrypoint.sh#
#    command: /app/entrypoint.sh


volumes:
  media_volume:
  # static_volume: